backend:
    build: ./Backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./Backend:/app
      - /app/vendor
    environment:
      DB_HOST: db
      DB_DATABASE: e_bourse_ugesm
      DB_USERNAME: root
      DB_PASSWORD: root